=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/System/Common/Schemes/KagaConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema erstellt mit Notepad++ v4.8.5 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="Version.xsd"/>
	<xs:element name="KagaConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Version"/>
				<xs:element ref="BusConfig" maxOccurs="1" minOccurs="0"/>
				<xs:element ref="NAT" maxOccurs="3" minOccurs="0"/>
				<xs:element ref="UserFilter" maxOccurs="10" minOccurs="0"/>
				<xs:element ref="BridgeInterface" maxOccurs="1" minOccurs="0"/>
				<xs:element ref="BandwidthLimits" maxOccurs="1" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BandwidthLimits">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="VirtualSendQueue" maxOccurs="5" minOccurs="0"/>
				<xs:element ref="StackSendQueue" maxOccurs="5" minOccurs="0"/>
				<xs:element ref="StackFIFO" maxOccurs="1" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StackSendQueue">
		<xs:complexType>
			<xs:attribute name="Interface" type="xs:string" use="required"/>
			<xs:attribute name="Bandwidth" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="StackFIFO">
		<xs:complexType>
			<xs:attribute name="Interface" type="xs:string" use="required"/>
			<xs:attribute name="NumElements" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="VirtualSendQueue">
		<xs:complexType>
			<xs:attribute name="Interface" type="xs:string" use="required"/>
			<xs:attribute name="Bandwidth" type="xs:int" use="required"/>
			<xs:attribute name="Limit" type="xs:int" use="required"/>
			<xs:attribute name="Timeout" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="BusConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PhysicalNetworkDevice" maxOccurs="1" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="isActive" type="xs:boolean" use="required"/>
			<xs:attribute name="Id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PhysicalNetworkDevice">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IfConfig"/>
				<xs:element ref="VirtualNetworkDevice" maxOccurs="10" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="HibernateSupport" type="xs:boolean" use="optional"/>
			<xs:attribute name="Priority" type="xs:unsignedByte" use="required"/>
			<xs:attribute name="LinkSettings" use="optional">
			   <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:enumeration value="10Mbit_HalfDuplex"/>
                  <xs:enumeration value="10Mbit_FullDuplex"/>
                  <xs:enumeration value="100Mbit_HalfDuplex"/>
                  <xs:enumeration value="100Mbit_FullDuplex"/>
                  <xs:enumeration value="1Gbit_FullDuplex"/>
                  <xs:enumeration value="Autonegotiation"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="IfConfig">
		<xs:complexType>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Unit" type="xs:unsignedByte" use="required"/>
			<xs:attribute name="IpConfigType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="IpnetStatic"/>
						<xs:enumeration value="IpnetDhcp"/>
						<xs:enumeration value="noIp"/>
						<xs:enumeration value="LwipStatic"/>
						<xs:enumeration value="LwipAndIpnetStatic"/>
                                    <xs:enumeration value="Auto"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Ip" type="xs:string" use="required"/>
			<xs:attribute name="Netmask" type="xs:string" use="required"/>
			<xs:attribute name="VLAN" type="xs:int" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="VirtualNetworkDevice">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IfConfig"/>
				<xs:element ref="Queue" maxOccurs="2" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Queue">
		<xs:complexType>
			<xs:sequence maxOccurs="5" minOccurs="1">
				<xs:element ref="Filter"/>
			</xs:sequence>
			<xs:attribute name="Priority" type="xs:unsignedByte" use="required"/>
			<xs:attribute name="Resources" type="xs:unsignedByte" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="NAT">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NATRule" type="xs:string" maxOccurs="40" minOccurs="0"/>
				<xs:element name="RouteRule" type="xs:string" maxOccurs="20" minOccurs="0"/>
            <xs:element ref="StandardGateway" maxOccurs="1" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="GlobalInterface" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Filter">
		<xs:complexType>
			<xs:attribute name="String" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="AcceptAll"/>
						<xs:enumeration value="DenyAll"/>
						<xs:enumeration value="Ip"/>
						<xs:enumeration value="EtherCat"/>
						<xs:enumeration value="KCP"/>
						<xs:enumeration value="ExactIp"/>
						<xs:enumeration value="Multicast"/>
						<xs:enumeration value="EthernetIP"/>
						<xs:enumeration value="UDP"/>
						<xs:enumeration value="VLAN"/>
						<xs:enumeration value="VLAN1"/>
						<xs:enumeration value="VLAN2"/>
						<xs:enumeration value="VLAN3"/>
						<xs:enumeration value="VLAN4"/>
						<xs:enumeration value="VLAN5"/>
						<xs:enumeration value="VLAN6"/>
						<xs:enumeration value="VLAN7"/>
						<xs:enumeration value="VLAN8"/>
						<xs:enumeration value="VLAN9"/>
						<xs:enumeration value="VLAN10"/>
						<xs:enumeration value="VLAN_IP"/>
						<xs:enumeration value="Filter0"/>
						<xs:enumeration value="Filter1"/>
						<xs:enumeration value="Filter2"/>
						<xs:enumeration value="Filter3"/>
						<xs:enumeration value="Filter4"/>
						<xs:enumeration value="Filter5"/>
						<xs:enumeration value="Filter6"/>
						<xs:enumeration value="Filter7"/>
						<xs:enumeration value="Filter8"/>
						<xs:enumeration value="Filter9"/>
						<xs:enumeration value="ProfinetRT"/>
						<xs:enumeration value="FWD_AUTOIP"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="BridgeInterface">
		<xs:complexType>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Unit" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="UserFilter">
		<xs:complexType>
			<xs:attribute name="Id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="Filter[0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ipProto"/>
						<xs:enumeration value="ip"/>
						<xs:enumeration value="blkIp"/>
						<xs:enumeration value="pkt"/>
						<xs:enumeration value="blkPkt"/>
						<xs:enumeration value="ecatvlan"/>
						<xs:enumeration value="acceptIp"/>
						<xs:enumeration value="denyVlan"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Attribute" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="StandardGateway">
		<xs:complexType>
			<xs:attribute name="Ip" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/User/Common/KONIConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<KagaConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/KagaConfig.xsd">
  <Version Label="">
    <Info Version="KUKA V8.3" />
    <Schema Version="300" />
  </Version>
  <BusConfig isActive="false" Id="NETWORK_CONFIG_KUKA_OPTION_NETWORK_INTERFACE">
    <PhysicalNetworkDevice Priority="13" HibernateSupport="true" LinkSettings="Autonegotiation">
      <IfConfig Name="gei" Unit="1" IpConfigType="noIp" Ip="none" Netmask="none" />
      <VirtualNetworkDevice>
        <!--INBETRIEBNAHME-TODO:
			1) @isActive des Elements /KagaConfig/BusConfig auf "true" setzen (aktiviert diese Konfiguration)
			2) @IpConfigType auf "IpnetStatic" abaendern (Bei DHCP: "IpnetDhcp")
			3) In @Ip die gewuenschte IP-Adresse eintragen (Bei DHCP: @Ip und @Netmask so belassen)
			Bsp:
			<IfConfig Name="KONI" Unit="20" IpConfigType="IpnetStatic" Ip="160.160.x.x" Netmask="ffff0000"/>
			-->
        <IfConfig Name="KONI" Unit="20" IpConfigType="IpnetStatic" Ip="172.30.1.147" Netmask="ffff0000" />
        <Queue Priority="255" Resources="100">
          <Filter String="AcceptAll" />
        </Queue>
      </VirtualNetworkDevice>
    </PhysicalNetworkDevice>
  </BusConfig>
  <NAT GlobalInterface="virtual20">
    <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 portmap tcp/udp 18000:18999</NATRule>
    <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 icmpidmap icmp 19000:19999</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 3389 -&gt; [host:WINDOWS] port 3389 tcp proxy RemoteIP</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 139 -&gt; [host:WINDOWS] port 139 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 445 -&gt; [host:WINDOWS] port 445 tcp/udp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49001 -&gt; [host:WINDOWS] port 49001 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49002 -&gt; [host:WINDOWS] port 49002 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49003 -&gt; [host:WINDOWS] port 49003 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49004 -&gt; [host:WINDOWS] port 49004 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49006 -&gt; [host:WINDOWS] port 49006 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49010 -&gt; [host:WINDOWS] port 49010 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 443 -&gt; [host:WINDOWS] port 443 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 4840 -&gt; [host:WINDOWS] port 4840 tcp</NATRule>
    <StandardGateway Ip="" />
  </NAT>
</KagaConfig>

=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/User/Common/KLIConfig.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?><KagaConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/KagaConfig.xsd">
  <Version Label="">
    <Info Version="KUKA V8.3"/>
    <Schema Version="400"/>
  </Version>
  <BusConfig Id="NETWORK_CONFIG_KUKA_LINE_INTERFACE" isActive="true">
    <PhysicalNetworkDevice HibernateSupport="true" LinkSettings="Autonegotiation" Priority="12">
      <IfConfig Ip="none" IpConfigType="noIp" Name="gei" Netmask="none" Unit="1"/>
      <VirtualNetworkDevice>
        <IfConfig Ip="192.168.1.32" IpConfigType="IpnetStatic" Name="KLI" Netmask="ffff0000" Unit="5"/>
        <Queue Priority="60" Resources="100">
          <Filter String="Filter2"/>
          <Filter String="Filter0"/>
          <Filter String="Filter1"/>
          <Filter String="EthernetIP"/>
        </Queue>
        <Queue Priority="255" Resources="100">
          <Filter String="Filter2"/>
          <Filter String="AcceptAll"/>
        </Queue>
      </VirtualNetworkDevice>
    </PhysicalNetworkDevice>
  </BusConfig>
  <NAT GlobalInterface="virtual5">
    <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 portmap tcp/udp 18000:18999</NATRule>
    <NATRule>map [GlobalNatInterface] [host:WINDOWS] -&gt; 0/32 icmpidmap icmp 19000:19999</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 3389 -&gt; [host:WINDOWS] port 3389 tcp proxy RemoteIP</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 139 -&gt; [host:WINDOWS] port 139 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 445 -&gt; [host:WINDOWS] port 445 tcp/udp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49001 -&gt; [host:WINDOWS] port 49001 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49002 -&gt; [host:WINDOWS] port 49002 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49003 -&gt; [host:WINDOWS] port 49003 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49004 -&gt; [host:WINDOWS] port 49004 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49006 -&gt; [host:WINDOWS] port 49006 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 49010 -&gt; [host:WINDOWS] port 49010 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 443 -&gt; [host:WINDOWS] port 443 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 50040 -&gt; [host:WINDOWS] port 50040 tcp</NATRule>
    <NATRule>rdr [GlobalNatInterface] [addr] port 4840 -&gt; [host:WINDOWS] port 4840 tcp</NATRule>
    <StandardGateway Ip="192.168.1.32"/>
  </NAT>
  <UserFilter Attribute="8100" Id="Filter0" Type="pkt"/>
  <UserFilter Attribute="8892" Id="Filter1" Type="pkt"/>
  <UserFilter Attribute="3" Id="Filter2" Type="denyVlan"/>
</KagaConfig>
