=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/System/Common/Schemes/NextGenDriveTech.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:include schemaLocation="NGVersion.xsd"/>
   <xs:element name="CommonConfig">
      <xs:complexType>
         <xs:attribute name="SdoPollIntervall">
            <xs:annotation>
               <xs:documentation>Update intervall for asynchronous data (e.g. motor temperatures) in [s] via SDO/CoE communication.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:double">
                  <xs:minInclusive value="0.5"/>
                  <xs:maxInclusive value="10.0"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="StopOnPhaseLoss" type="xs:boolean" use="optional" default="true">
            <xs:annotation>
               <xs:documentation>true = use status messages with stop reaction for phase loss and net loss warnings.
                                 false = use notification messages without stop reaction for phase loss and net loss warnings.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="TickTockActivated" type="xs:boolean" use="optional" default="true">
            <xs:annotation>
               <xs:documentation>true = CF uses Tick-Tock-Mode. One CF-cycle is for controller calculation the other for bus communication.
                                 false = CF uses standard control cycle. Controller calculation and communication each CF-cycle.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="SuppressResetingRefSineSettings" type="xs:boolean" use="optional" default="true">
            <xs:annotation>
               <xs:documentation>Obsolete.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="UseAdaptiveRampStop" type="xs:boolean" use="optional" default="true">
            <xs:annotation>
               <xs:documentation>true = adaptive recalculation of stop ramps is used. Stop deceleration will be aggravated according to brake reserve factor (based on torque load, etc.).
                                 false = adaptive recalculation of stop ramps is deactivated. Ramp stop will be performed according to 'RampStopTime' or 'RampStopTimeWithBrake'</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="Axis">
      <xs:complexType>
         <xs:attribute name="ID" use="required">
            <xs:simpleType>
               <xs:restriction base="xs:int">
                  <xs:minInclusive value="1"/>
                  <xs:maxInclusive value="255"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="SupplyChannel" use="required">
            <xs:simpleType>
               <xs:restriction base="xs:int">
                  <xs:minInclusive value="1"/>
                  <xs:maxInclusive value="16"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="RampStopGroup" use="optional" default="1">
            <xs:simpleType>
               <xs:restriction base="xs:int">
                  <xs:minInclusive value="1"/>
                  <xs:maxInclusive value="32"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="ConfigFile" type="xs:string" use="required"/>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="tSensor">
      <xs:attribute name="ID" use="required">
         <xs:simpleType>
            <xs:restriction base="xs:int">
               <xs:minInclusive value="1"/>
               <xs:maxInclusive value="255"/>
            </xs:restriction>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="ConfigFile" type="xs:string"/>
   </xs:complexType>
   <xs:element name="AxisConfig">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Axis" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="tSensorConfig">
      <xs:sequence>
         <xs:element name="Sensor" type="tSensor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="DriveTech">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Version" minOccurs="0" />
            <xs:element ref="AxisConfig"/>
            <xs:element name="SensorConfig" type="tSensorConfig" minOccurs="0"/>
            <xs:element name="SupplyConfig">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="Supply" minOccurs="0" maxOccurs="10">
                        <xs:complexType>
                           <xs:attribute name="Setup" type="xs:string" use="optional"/>
                           <xs:attribute name="NominalSupplyVoltage" type="xs:double" use="optional"/>
                           <xs:attribute name="MinSupplyVoltage" type="xs:double" use="optional"/>
                           <xs:attribute name="MaxSupplyVoltage" type="xs:double" use="optional"/>
                           <xs:attribute name="PowerConsumptionRunning" type="xs:double" use="optional"/>
                           <xs:attribute name="PowerConsumptionBusPowerOff" type="xs:double" use="optional"/>
                           <xs:attribute name="PowerConsumptionSoftPowerOff" type="xs:double" use="optional"/>
                           <xs:attribute name="Capacity" type="xs:double" use="optional"/>
                           <xs:attribute name="ConfigFile" type="xs:string" use="required"/>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            <xs:element name="FastMeasuring">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="Channel" minOccurs="0" maxOccurs="16">
                        <xs:complexType>
                           <xs:attribute name="ID" use="required">
                              <xs:simpleType>
                                 <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                 </xs:restriction>
                              </xs:simpleType>
                           </xs:attribute>
                           <xs:attribute name="Description" type="xs:string" use="required"/>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            <xs:element ref="CommonConfig" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/User/Common/Mada/NextGenDriveTech.xml
<?xml version="1.0" encoding="utf-8"?>
<!--XML file automatically generated by WorkVisual V6.0.31_Build3247.-->
<!--DO NOT EDIT-->
<DriveTech xsi:noNamespaceSchemaLocation="../../../System/Common/Schemes/NextGenDriveTech.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Version Label="">
    <Info Version="KUKA V8.7" />
    <Schema Version="3" />
  </Version>
  <AxisConfig>
    <Axis ID="1" SupplyChannel="1" ConfigFile="Mada\NGAxis\A1.xml" />
    <Axis ID="2" SupplyChannel="1" ConfigFile="Mada\NGAxis\A2.xml" />
    <Axis ID="3" SupplyChannel="1" ConfigFile="Mada\NGAxis\A3.xml" />
    <Axis ID="4" SupplyChannel="1" ConfigFile="Mada\NGAxis\A5.xml" />
    <Axis ID="5" SupplyChannel="1" ConfigFile="Mada\NGAxis\A6.xml" />
  </AxisConfig>
  <SensorConfig />
  <SupplyConfig>
    <Supply Setup="AC" NominalSupplyVoltage="560" ConfigFile="Supply/KPP600-67L_380V_3200.xml" />
  </SupplyConfig>
  <FastMeasuring />
  <CommonConfig SdoPollIntervall="2" StopOnPhaseLoss="true" TickTockActivated="true" />
</DriveTech>
