=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/System/Common/Schemes/ServoFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2008 (http://www.altova.com) von Stolte (KUKA Deutschland GmbH) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="NGVersion.xsd"/>
	<xs:simpleType name="ValueType">
		<xs:restriction base="xs:string">
         <xs:enumeration value="INT8"/>
         <xs:enumeration value="UINT8"/>
			<xs:enumeration value="INT16"/>
			<xs:enumeration value="UINT16"/>
         <xs:enumeration value="INT32"/>
         <xs:enumeration value="UINT32"/>
			<xs:enumeration value="FLOAT32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DestinationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Servo"/>
			<xs:enumeration value="Supply"/>
			<xs:enumeration value="PositionSensor"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="ServoFile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Version" minOccurs="0" />
				<xs:sequence>
					<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="Index" type="xs:string" use="required">
								<xs:annotation>
									<xs:documentation>SDO-Index 0..65535 or 0x0..0x7FFF (uppercase)</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="Relative" type="xs:boolean" use="required">
								<xs:annotation>
									<xs:documentation>relative Index for device functionality (e.g. KSP has 3  identical drive segments with different offsets)</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="SubIndex" use="required">
								<xs:annotation>
									<xs:documentation>SDO-Subindex 0..255</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="255"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="Type" type="ValueType" use="required">
								<xs:annotation>
									<xs:documentation>supported types: "INT8", "UINT8", "INT16", "UINT16", "INT32", "UINT32", "FLOAT32"</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="Value" type="xs:string" use="required">
								<xs:annotation>
									<xs:documentation>value as string, is checked when read</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="Destination" type="DestinationType">
								<xs:annotation>
									<xs:documentation>"Servo" (default), "Supply", "PositionSensor"</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/User/Common/ServoFile/S_KPP600-67L_380V_3200.xml
<?xml version="1.0" encoding="utf-8"?>
<!--XML file automatically generated by WorkVisual V6.0.31_Build3247.-->
<!--DO NOT EDIT-->
<ServoFile xsi:noNamespaceSchemaLocation="../../../System/Common/Schemes/Servofile.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!--#############################################################-->
  <!--########                                             ########-->
  <!--########                  SERVO-FILE                 ########-->
  <!--########             KUKA DEUTSCHLAND GMBH           ########-->
  <!--########                                             ########-->
  <!--#############################################################-->
  <!--ATB 3.0.7, DB V8.521, ID 1000003, V8.7.4-->
  <!--Datum: 17-Mar-2022 06:45:07-->
  <!--Control: KPP600-67L-->
  <Parameter Index="0x5031" Relative="false" SubIndex="1" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="2" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="3" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="4" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="5" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="6" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="7" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="8" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="9" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="10" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="11" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="12" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="13" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="14" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="15" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5031" Relative="false" SubIndex="16" Type="INT32" Value="0x50470003" />
  <Parameter Index="0x5040" Relative="false" SubIndex="4" Type="UINT16" Value="3200" />
  <Parameter Index="0x5040" Relative="false" SubIndex="5" Type="UINT16" Value="11" />
  <Parameter Index="0x5043" Relative="false" SubIndex="2" Type="FLOAT32" Value="775" />
  <Parameter Index="0x5043" Relative="false" SubIndex="3" Type="FLOAT32" Value="755" />
</ServoFile>

=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/User/Common/ServoFile/S_SI-M4800-KM192-W0_KSP600-64_380V_V1.xml
<?xml version="1.0" encoding="utf-8"?>
<ServoFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/Servofile.xsd">
  <Version Label="">
    <Info Version="8.7.2" />
    <Schema Version="1" />
    <!--###############################################################-->
    <!--########                                               ########-->
    <!--########                     KR C5                     ########-->
    <!--########                  Servo-File                   ########-->
    <!--########             KUKA DEUTSCHLAND GMBH             ########-->
    <!--########                                               ########-->
    <!--###############################################################-->
    <!--ATB 3.0.7, DB V8.585, ID 1000070-->
    <!--Datum: 25-May-2022 17:21:37-->
    <!--Motor:     SI-M4800-KM192-W0-->
    <!--Umrichter: KSP600-64-->
    <!--xmlFileID_SI-M4800-KM192-W0_KSP600-64_20220525172137_108-->
  </Version>
  <Parameter Index="11776" Relative="false" SubIndex="9" Type="UINT8" Value="1" />
  <Parameter Index="3" Relative="true" SubIndex="1" Type="UINT16" Value="0" />
  <Parameter Index="6" Relative="true" SubIndex="3" Type="FLOAT32" Value="64" />
  <Parameter Index="8" Relative="true" SubIndex="1" Type="FLOAT32" Value="45.3" />
  <Parameter Index="8" Relative="true" SubIndex="3" Type="FLOAT32" Value="0.0064472" />
  <Parameter Index="8" Relative="true" SubIndex="4" Type="FLOAT32" Value="0.85" />
  <Parameter Index="8" Relative="true" SubIndex="7" Type="FLOAT32" Value="1" />
  <Parameter Index="8" Relative="true" SubIndex="8" Type="FLOAT32" Value="0" />
  <Parameter Index="8" Relative="true" SubIndex="9" Type="FLOAT32" Value="0" />
  <Parameter Index="8" Relative="true" SubIndex="11" Type="FLOAT32" Value="0" />
  <Parameter Index="9" Relative="true" SubIndex="1" Type="FLOAT32" Value="4.75" />
  <Parameter Index="9" Relative="true" SubIndex="2" Type="FLOAT32" Value="0.15" />
  <Parameter Index="9" Relative="true" SubIndex="3" Type="FLOAT32" Value="4.75" />
  <Parameter Index="9" Relative="true" SubIndex="4" Type="FLOAT32" Value="0.15" />
  <Parameter Index="9" Relative="true" SubIndex="5" Type="FLOAT32" Value="0.0025686" />
  <Parameter Index="9" Relative="true" SubIndex="7" Type="FLOAT32" Value="0.15417" />
  <Parameter Index="9" Relative="true" SubIndex="12" Type="FLOAT32" Value="-57.0988" />
  <Parameter Index="9" Relative="true" SubIndex="13" Type="UINT8" Value="1" />
  <Parameter Index="9" Relative="true" SubIndex="14" Type="FLOAT32" Value="200" />
  <Parameter Index="11" Relative="true" SubIndex="1" Type="FLOAT32" Value="1.0238" />
  <Parameter Index="11" Relative="true" SubIndex="2" Type="FLOAT32" Value="1.1733" />
  <Parameter Index="11" Relative="true" SubIndex="3" Type="FLOAT32" Value="1.2026" />
  <Parameter Index="11" Relative="true" SubIndex="4" Type="FLOAT32" Value="1.1892" />
  <Parameter Index="11" Relative="true" SubIndex="5" Type="FLOAT32" Value="1.1716" />
  <Parameter Index="11" Relative="true" SubIndex="6" Type="FLOAT32" Value="1.1517" />
  <Parameter Index="11" Relative="true" SubIndex="7" Type="FLOAT32" Value="1.1307" />
  <Parameter Index="11" Relative="true" SubIndex="8" Type="FLOAT32" Value="1.1098" />
  <Parameter Index="11" Relative="true" SubIndex="9" Type="FLOAT32" Value="1.09" />
  <Parameter Index="11" Relative="true" SubIndex="10" Type="FLOAT32" Value="1.0717" />
  <Parameter Index="11" Relative="true" SubIndex="11" Type="FLOAT32" Value="1.0553" />
  <Parameter Index="11" Relative="true" SubIndex="12" Type="FLOAT32" Value="1.0407" />
  <Parameter Index="11" Relative="true" SubIndex="13" Type="FLOAT32" Value="1.0276" />
  <Parameter Index="11" Relative="true" SubIndex="14" Type="FLOAT32" Value="1.0158" />
  <Parameter Index="11" Relative="true" SubIndex="15" Type="FLOAT32" Value="1.005" />
  <Parameter Index="11" Relative="true" SubIndex="16" Type="FLOAT32" Value="0.99478" />
  <Parameter Index="11" Relative="true" SubIndex="17" Type="FLOAT32" Value="0.98497" />
  <Parameter Index="11" Relative="true" SubIndex="18" Type="FLOAT32" Value="0.97538" />
  <Parameter Index="11" Relative="true" SubIndex="19" Type="FLOAT32" Value="0.96588" />
  <Parameter Index="11" Relative="true" SubIndex="20" Type="FLOAT32" Value="0.9564" />
  <Parameter Index="11" Relative="true" SubIndex="21" Type="FLOAT32" Value="0.94692" />
  <Parameter Index="11" Relative="true" SubIndex="22" Type="FLOAT32" Value="0.93742" />
  <Parameter Index="11" Relative="true" SubIndex="23" Type="FLOAT32" Value="0.92794" />
  <Parameter Index="11" Relative="true" SubIndex="24" Type="FLOAT32" Value="0.91848" />
  <Parameter Index="11" Relative="true" SubIndex="25" Type="FLOAT32" Value="0.90908" />
  <Parameter Index="11" Relative="true" SubIndex="26" Type="FLOAT32" Value="0.89978" />
  <Parameter Index="11" Relative="true" SubIndex="27" Type="FLOAT32" Value="0.8906" />
  <Parameter Index="11" Relative="true" SubIndex="28" Type="FLOAT32" Value="0.88158" />
  <Parameter Index="11" Relative="true" SubIndex="29" Type="FLOAT32" Value="0.87275" />
  <Parameter Index="11" Relative="true" SubIndex="30" Type="FLOAT32" Value="0.86413" />
  <Parameter Index="11" Relative="true" SubIndex="31" Type="FLOAT32" Value="0.85574" />
  <Parameter Index="11" Relative="true" SubIndex="32" Type="FLOAT32" Value="0.8476" />
  <Parameter Index="11" Relative="true" SubIndex="33" Type="FLOAT32" Value="0.83974" />
  <Parameter Index="12" Relative="true" SubIndex="2" Type="UINT8" Value="0" />
  <Parameter Index="67" Relative="true" SubIndex="1" Type="FLOAT32" Value="0.3" />
  <Parameter Index="67" Relative="true" SubIndex="2" Type="FLOAT32" Value="0.75262" />
  <Parameter Index="67" Relative="true" SubIndex="3" Type="FLOAT32" Value="0.3" />
  <Parameter Index="67" Relative="true" SubIndex="4" Type="FLOAT32" Value="1.9111" />
  <Parameter Index="68" Relative="true" SubIndex="2" Type="FLOAT32" Value="24" />
  <Parameter Index="68" Relative="true" SubIndex="3" Type="FLOAT32" Value="1" />
</ServoFile>
<!--checksum 7972-->
