=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/System/Common/Schemes/WaggonDriverConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2008 (http://www.altova.com) von XMLSPY 2006 Professional Ed. Release 3, Concurrent for 5 users (with SMP from 2006-10-19 to 2007-10-20) (KUKA Deutschland GmbH) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:include schemaLocation="NGVersion.xsd"/>
   <!--todo <xs:redefine schemaLocation="NGVersion.xsd">-->
   <!-- *************************************************
       min- and maxInclusive have to be the same value
       this value has to be changed on every change of this file !!
       *************************************************** -->
   <!--<xs:simpleType name="VersionType">
       <xs:restriction base="VersionType">
          <xs:minInclusive value="1"/> 
          <xs:maxInclusive value="1"/>
       </xs:restriction>
    </xs:simpleType>
 </xs:redefine>-->
   <xs:include schemaLocation="Units.xsd"/>
   <xs:include schemaLocation="WaggonDriverCommon.xsd"/>
   <xs:simpleType name="T_Occurrence">
      <xs:annotation>
         <xs:documentation> type to select an offset from ambigous offset definitions </xs:documentation>
      </xs:annotation>
      <xs:restriction base="xs:nonNegativeInteger"/>
   </xs:simpleType>
   <xs:element name="VendorID">
      <xs:simpleType>
         <xs:restriction base="xs:integer"/>
      </xs:simpleType>
   </xs:element>
   <xs:element name="ProductCode">
      <xs:simpleType>
         <xs:restriction base="xs:integer"/>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Substring">
      <xs:simpleType>
         <xs:restriction base="xs:string"/>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Offset">
      <xs:complexType>
         <xs:attribute name="VendorID" type="xs:int" use="optional">
            <xs:annotation>
               <xs:documentation>Vendor ID of device(s) to use for process data variable mapping from EtherCAT configuration file</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="ProductCode" type="xs:int" use="optional">
            <xs:annotation>
               <xs:documentation>Product code of device(s) to use for process data variable mapping from EtherCAT configuration file</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="RevisionNo" type="xs:int" use="optional">
            <xs:annotation>
               <xs:documentation>Not used any more.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="Occurrence" type="T_Occurrence" use="optional">
            <xs:annotation>
               <xs:documentation>Index of occurrence of process data variable in EtherCAT configuration file starting with 0 or "all"</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="VarName" type="xs:string" use="optional">
            <xs:annotation>
               <xs:documentation>Name of process data variable in EtherCAT configuration file</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="WDVarDescription" type="xs:string" use="optional">
            <xs:annotation>
               <xs:documentation>Optional meaning of offset for the waggon driver associated</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="RevisionNoMask" type="xs:unsignedInt" use="optional">
            <xs:annotation>
               <xs:documentation>Not used any more.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="ByteOffset" type="xs:int" use="optional">
            <xs:annotation>
               <xs:documentation>ByteOffset</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="BitOffset" type="xs:int" use="optional">
            <xs:annotation>
               <xs:documentation>BitOffset</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="BitSize" type="xs:int" use="optional">
            <xs:annotation>
               <xs:documentation>BitSize</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="DataType" type="xs:string" use="optional">
            <xs:annotation>
               <xs:documentation>DataType</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="Input">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Offset" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="Output">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Offset" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="WaggonDriver">
      <xs:complexType>
         <xs:sequence>
            <xs:sequence/>
            <xs:sequence>
               <xs:element ref="Input" minOccurs="0"/>
               <xs:element ref="Output" minOccurs="0"/>
            </xs:sequence>
            <xs:element name="AdditionalOffsets" minOccurs="0" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:documentation>obsolete</xs:documentation>
               </xs:annotation>
               <xs:complexType>
                  <xs:sequence>
                     <xs:element ref="Input" minOccurs="0"/>
                     <xs:element ref="Output" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
         <xs:attribute ref="ID" use="required"/>
         <xs:attribute ref="Bus" use="optional"/>
         <xs:attribute ref="BusDriver" use="optional"/>
         <xs:attribute ref="BusInstance" use="optional"/>
         <xs:attribute ref="ConfigFile" use="optional"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="WaggonDriverConfig">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Version" minOccurs="0" />
            <xs:element ref="WaggonDriver" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== SilvestrLiskin/kuka-krl-extension/Cell PCRC-MJ5RG3TVKW_PCRC-QLWXUWPQS7_Ambalajli_Paletleme_Robotu_996627/C/KRC/Roboter/Config/User/Common/Mada/CFCoreWaggonDriverConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<!--XML file automatically generated by WorkVisual V6.0.31_Build3247.-->
<!--DO NOT EDIT-->
<WaggonDriverConfig xsi:noNamespaceSchemaLocation="../../../System/Common/Schemes/WaggonDriverConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Version Label="">
    <Info Version="KUKA V8.7" />
    <Schema Version="1" />
  </Version>
  <WaggonDriver ID="106">
    <!--KPP-Supply Daten-Kanal 1 von KPP-->
    <Input>
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive In.Supplier status" Occurrence="0" />
    </Input>
    <Output>
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive Out.Supplier control" Occurrence="0" />
    </Output>
  </WaggonDriver>
  <WaggonDriver ID="100">
    <!--CCFRDC3 Resolver Digital Converter-->
    <Input>
      <Offset VendorID="24776" ProductCode="48" VarName="FSoE-Drive In.Position 1" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="48" VarName="FSoE-Drive In.Position 2" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="48" VarName="FSoE-Drive In.Position 3" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="48" VarName="FSoE-Drive In.Position 4" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="48" VarName="FSoE-Drive In.Position 5" Occurrence="0" />
    </Input>
    <AdditionalOffsets type="global">
      <Input>
        <Offset VendorID="24776" ProductCode="48" VarName="FSoE-Drive In.Command" Occurrence="0" WDVarDescription="RDC-Global-Data" />
      </Input>
    </AdditionalOffsets>
  </WaggonDriver>
  <WaggonDriver ID="101">
    <!--KSP-Daten-Kanaele von KSP-->
    <Input>
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive In.Motor status 1" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive In.Motor status 2" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive In.Motor status 3" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive In.Motor status 5" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive In.Motor status 6" Occurrence="0" />
    </Input>
    <Output>
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive Out.Motor control 1" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive Out.Motor control 2" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive Out.Motor control 3" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive Out.Motor control 5" Occurrence="0" />
      <Offset VendorID="24776" ProductCode="131" VarName="FSoE-Drive Out.Motor control 6" Occurrence="0" />
    </Output>
  </WaggonDriver>
</WaggonDriverConfig>
